# Generated by Django 5.0.6 on 2024-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (0, 'Female')]),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
