# Generated by Django 5.0.6 on 2024-07-15 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('participants', '0002_alter_participant_gender'),
        ('tournaments', '0002_alter_tournament_gender_alter_tournament_max_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalsPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_pairs', to='competitions.competition')),
                ('participant1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_participant1_pairs', to='participants.participant')),
                ('participant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finals_participant2_pairs', to='participants.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_pairs', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finals_won_pairs', to='participants.participant')),
            ],
        ),
        migrations.CreateModel(
            name='FinalsParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_participants', to='competitions.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_participants', to='participants.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_participants', to='tournaments.tournament')),
            ],
        ),
    ]
