# Generated by Django 5.0.6 on 2024-07-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalspair',
            name='stage',
            field=models.CharField(choices=[('final', 'Final'), ('half-final', 'Half-Final'), ('quarter-final', 'Quarter-Final')], max_length=50),
        ),
    ]
