# Generated by Django 5.0.6 on 2024-07-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finals', '0002_alter_finalspair_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalspair',
            name='participant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finals_participant1_pairs', to='finals.finalsparticipant'),
        ),
        migrations.AlterField(
            model_name='finalspair',
            name='participant2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finals_participant2_pairs', to='finals.finalsparticipant'),
        ),
        migrations.AlterField(
            model_name='finalspair',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finals_won_pairs', to='finals.finalsparticipant'),
        ),
    ]
